stocks:
  - ticker: "MSFT"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "AMZN"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "NVDA"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
num_simulations: 20
time_horizon: 252  