stocks:
  - ticker: "META"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "AAPL"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
num_simulations: 5000000
time_horizon: 252  # One trading year