stocks:
  - ticker: "MSFT"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "AMZN"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "NVDA"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "MU"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "CRSP"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "PLTR"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "SMCI"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "CEG"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "DUK"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "NEE"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "SO"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
  - ticker: "D"
    start_date: "2020-01-01"
    end_date: "2024-08-07"
num_simulations: 50000
time_horizon: 756